server:
  port: 8020

spring:
  application:
    name: rm-message-consumer

  # 配置 RabbitMQ 消息队列：队列配置见底部
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

# 配置服务注册
eureka:
  instance:
    # 将自己的IP注册到 Eureka Server，false 表示注册微服务所在操作系统的 hostname 到 Eureka Server
    prefer-ip-address: true
  client:
    serviceUrl:
      # 服务注册（无需密码）
      defaultZone: http://localhost:8761/eureka
      # 服务注册（需要密码），格式：http://username:password@EUREKA_HOST:EUREKA_PORT/eureka/
#      defaultZone: http://user:password123@localhost:8761/eureka/

# 禁用 Feign 的 Hystrix，不使用断路器
feign:
  hystrix:
    enabled: false

# 配置日志级别，让 hibernate 打印执行的SQL
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
debug: true

## 启用 Actuator 后，访问 host:port/info 显示以下信息；占位符引用 Maven 配置信息
info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

# 配置队列名称，创建队列的任务由 com.hason.dtp.account.config.MQConfig 完成
queue:
  message:
    # 用户积分计算队列
    userPointQueue: ms-dtp-user-point-queue